### ISSUE TITLE
[Meta] Exam Mode

### ISSUE THREAD

**Issue by jpbernius** [ls1intum/Artemis#1565]
This is a meta issue tracking progress for the [**Exam mode**](/ls1intum/Artemis/labels/exam%20mode) feature. We use this issue to track milestone progress and link to the individual requirements.

## Milestone 1:
- [x] Performance improvements, scaling to multiple server/services, improvement of availability if 1 server fails
- [x] Exercise Variant Management: Allow an instructor to define multiple exercises and generate unique individual exam configurations for students: [adjust data model](https://github.com/ls1intum/Artemis/issues/1564), [student exam overview](https://github.com/ls1intum/Artemis/issues/1624), [import students from csv](https://github.com/ls1intum/Artemis/issues/1623), [student overview](https://github.com/ls1intum/Artemis/issues/1622), [adjust exercise create/update dialogues](https://github.com/ls1intum/Artemis/issues/1621), [exercise groups](https://github.com/ls1intum/Artemis/issues/1620), [create and update an exam](https://github.com/ls1intum/Artemis/issues/1619), [exam overview](https://github.com/ls1intum/Artemis/issues/1618), [exam assessment dashboard](https://github.com/ls1intum/Artemis/issues/1617), [add database constraint](https://github.com/ls1intum/Artemis/issues/1615), [generate participations before exam start](https://github.com/ls1intum/Artemis/issues/1616) 
- [x] Exam mode: quick navigation between exercises and offline support, clear status display for each exercise: [main component](https://github.com/ls1intum/Artemis/issues/1568), [exam header bar](https://github.com/ls1intum/Artemis/issues/1570), [summary](https://github.com/ls1intum/Artemis/issues/1569), [offline mode](https://github.com/ls1intum/Artemis/issues/1572), [create start and final view](https://github.com/ls1intum/Artemis/issues/1583), [start view](https://github.com/ls1intum/Artemis/issues/1582), [final view](https://github.com/ls1intum/Artemis/issues/1578) , [modeling exercises](https://github.com/ls1intum/Artemis/issues/1589), [text exercises](https://github.com/ls1intum/Artemis/issues/1588), [file-upload exercises](https://github.com/ls1intum/Artemis/issues/1587), [connection footer](https://github.com/ls1intum/Artemis/issues/1607)
- [x] IP Logging ++ #1566

## Milestone 2:
- [x] Online Editor Only https://github.com/ls1intum/Artemis/pull/1680
- [x] Batch Start
- [x] PDF Export
- [ ] Session Management
- [x] Images in Problem Statements

## Optional:
- [x] Progress indicator
- [ ] Export
- [x] Import exercises
- [ ] Student Questions during Exams

---
ℹ️ Please update this issues with references to issues. Discussions should happen in referenced issues.

**Comment by krusche** [comment]
We finished a first iteration of the exam mode, this meta issue is not needed any more
