### ISSUE TITLE
[Exam] IP Logging++

### ISSUE THREAD

**Issue by jpbernius** [ls1intum/Artemis#1566]
We want to log the IP Addresses and other connection data of students while they participate in an Artemis exam. We want to create a fingerprint (as ofter used in advertising) to limit track whether multiple people try to participate as one student.

- IP Address
- Browser
- Operating System
- Fingerprint
- Store unique identifier in local storage
- ...

We need to collect this information on the client (and on the server as well on request?) and persist it in the database.

#### Open questions:
- When to store this data? Always or only during exams?
- Do we need to get user consent?
- Do we need to update our privacy policy?
- How long do we store this?

### Progress

- [x] Client: Compute Fingerprint #1688
- [x] Client: Instance Identifier in Local Storage #1688
- [ ] Server: Persist IP Address #1808
- [x] Server: Persist Fingerprint
- [x] Server: Persist Instance Identifier
- [x] Server: Link Session with Student Exam

**Comment by SimonPannek** [comment]
**When to store this data? Always or only during exams?**
Just a concern: Keep in mind that some of the users are using multiple devices/browsers which would lead to false flags for the same user if someone decided to switch.
This would be less of a concern if you would only store the data during exams but even then someone may have problems with a device/the network connection and might switch to another device or start using a mobile hotspot.

**Comment by jpbernius** [comment]
After discussing this feature with @balazs-czopf, we decided to combine IP Logging with Session management.
IP addresses should be logged in the context of a session. Further, we plan to use [fingerprintjs.com](https://fingerprintjs.com) to generate a unique browser fingerprint string.

Fingerprint and spring session id should be stored as part of a new `Session` entity. The session can have multiple `connections` (effectively IP addresses) associated with it. (You stay logged in when changing internet connection).
When submitting exercises, we want to create links between `submissions` and `sessions` (**this is open for discussion, we can also move this to participation?**).
<img width="100%" alt="image" src="https://user-images.githubusercontent.com/6382716/84595720-cd6cbf80-ae59-11ea-9480-767b82f21f53.png">
From this Session, we can also generate a **session TAN** which we could display in the header and collect from students with Student IDs? (@krusche @nvf we might want to take this into our Monday meeting?)

The browser fingerprint will be added to **all** network calls in an HTTP header (from an Angular Network Interceptor) and fetched for all (or selected) requests using a Spring Filter. We will need application logic to link submissions with sessions.

For now, we only store those identifiers. We can use this **after** the exam to inspect individual submissions more closely.

### Performance Implications
- Computation of browser fingerprint is only on the client-side and will only read a few properties (e.g. IP, browser version, installed fonts, etc.) and compute a hash once. This will not impact client performance.
- For all (or selected) requests, we need to create/update the session and (if necessary) store a new IP address. This can most likely be done in one simple database query. While an extra query, this will be a simple and fast query, especially compared to other queries needed in our application logic.
- Storage:
    - IP addresses consume a 15 OR 39 character string (v4 vs v6)
    - Browser Fingerprint (22character string)
    - User agents are longer strings ([fun story](https://webaim.org/blog/user-agent-string-history/)), we already store them in the audit log sometimes without issues. 
- future development: This is the most important implication! We need to update the application always in the future to update links between submissions and sessions.

### Alternative Options
- Link with participation instead of submission
- Log IP, fingerprint, etc as Audit event and try to match later
- try to match based on timestamps, but this is less accurate!
- We can try to update all submission/session links from a Filter. in this case, however, we need to identify all submissions/participations entities from URLs and fetch them in the filter. I think this is not preferred from performance or maintainability sides.

---
@ls1intum/artemis @krusche:
Please review the suggested approach, especially in terms of the data model changes and add a :+1: reaction if you approve or :-1: if you suggest changes. Please propose changes in a comment.
Feel free to react with 👀 when you are currently reviewing.

**Comment by krusche** [comment]
Thanks for starting the discussion and adding all the details here. Yes, let's discuss this personally in our instructor meeting on Monday 👍 

Regarding the session management: I discussed with @balazs-czopf that the session token should be bound to `StudentExam`, either as attribute `sessionToken` directly in the StudentExam or as referenced object to StudentExam (e.g. called `StudetExamSession`). The idea was that students can only save submissions in exam exercises if the latest `sessionToken` (references by their `StudentExam`) is present in the header of the corresponding REST call.

Every time a student enters the exam mode, the student needs to (confirm and) click start in the start screen (even if the student has already started the exam before). The start button triggers the creation of a new `sessionToken` that basically invalidates the old one (in case one is existing). The `sessionToken` is returned to the client and stored in a way that it can easily be added to the save submission REST calls.

Without the newest `sessionToken` in the header of the REST call, students cannot save the exam exercise submissions which is shown as an error message. Then, they must "start" the exam again  based on the latest stored server progress (we could still think about keeping their latest client progress in the browser cache).

In case, we store the `sessionToken` in a separate object `StudetExamSession` with a one to many association from `StudentExam`, we could also store a timestamp (and additional data such as browser fingerprinting). Then, during save submission in exam exercises, Artemis would always check the `sessionToken` against the newest `StudetExamSession`, which would automatically invalidate old ones.
