### ISSUE TITLE
[Meta] Improve Test Coverage

### ISSUE THREAD

**Issue by schultek** [ls1intum/Artemis#2080]
This is a meta issue tracking the progress for improving the test coverage across Artemis.

1. [Confluence Page](https://confluence.ase.in.tum.de/x/ni_rAw)
2. [Client Coverage Report](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS-1321/artifact/shared/Coverage-Report-Client-Tests/index.html)
3. [Server Coverage Report](https://bamboo.ase.in.tum.de/browse/ARTEMIS-TESTS-1321/artifact/shared/Coverage-Report-Server-Tests/index.html)

## Server Issues

- [ ] #2079 Improve test coverage for LTIService
- [ ] #2078 Improve test coverage for BitbucketService and BambooService
- [ ] #2077 Improve test coverage for GitlabService and JenkinsService
