### ISSUE TITLE
Local Version Control and Continuous Integration - MA

### ISSUE THREAD

**Issue by frederik-kt** [ls1intum/Artemis#5873]
### Is your feature request related to a problem?

Setting up the local development environment is a tedious process. Multiple Docker containers must be started and configured to connect Artemis to the external Version Control and Continuous Integration systems (either Bitbucket + Bamboo or Gitlab + Jenkins). Connecting to the external systems for the creation of repositories and build plans is also slow. In addition, the external systems require a number of workarounds including the development of plugins for Bamboo and Jenkins. At the same time, Artemis only uses a small part of the functionality of the before mentioned systems.

### Describe the solution you'd like

Local Version Control and Continuous Integration systems should be implemented as a part of Artemis, thereby improving the developer experience and making Artemis faster.

### ToDos

**VC**

- [x] Creating a programming exercise generates template, solution, and test repositories.
- [x] Students can participate in an exercise using the online editor. 
- [x] Students can participate in an exercise using their local git client. -> make sure the UI reflects the choice of local repositories
- [x] Fetching source code for a programming exercise is authenticated.
- [x] Pushing source code for a programming exercise is authenticated.
- [x] Creating an exam generates template, solution, and test repositories.
- [x] Students can participate in an exam using the online editor.
- [x] Students can participate in an exam using their local git client. 
- [x] Fetching source code for an exam is authenticated.
- [x] Pushing source code for an exam is authenticated.

**CI**

- [x] Remove Auxiliary Repositories in the UI for when profile "localci" is active.
- [x] Creating a Java programming exercise generates BASE and SOLUTION build plans.
- [x] Instructors can verify the exercise configuration via the SOLUTION build plan.
- [x] When a student participates in a Java exercise, a personal build plan is created.
- [x] When a student pushes a new solution submission, a build job created from their personal build plan is executed.
- [x] The results from the build job execution are displayed correctly.
- [x] Creating a Java exam generates the correct build plans.
- [x] Student exam submissions are evaluated correctly.
- [x] Student exam results are displayed correctly.

**Comment by dfuchss** [comment]
One of the main reasons for Jenkins and other CI systems is that you can easily scale the whole system using worker nodes.
Is the local CI only meant for Developers and the Dev Process ?

**Comment by krusche** [comment]
The main purpose is to make it easier for new administrators to try out Artemis without having too much overhead. This approach could also allow one click cloud setups.

It will also make it easier for developers to test programming exercise features. 

In case the approach works nicely, we also consider implementing some kind of simple approach for worker nodes. In fact a distributed build queue would be simple to implement using Hazelcast. Then multi-node deployments with multiple Artemis application servers could already run several jobs at the same time and directly save the result in the database (without the need to maintain plugins, etc.) 

At TUM, we have 11 application servers which most of the time have quite a low CPU usage. Those application servers could definitely use some of their CPU power for CI builds.
