### ISSUE TITLE
Tracking Discussion: Required steps for GitLab to LocalVC migration

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#8754]
### Is your feature request related to a problem?

Like the migration from BitBucket to LocalVC, a similar automatic migration should be possible for the migration from GitLab to LocalVC.

This issue serves as a collection/tracker to discuss required steps for this to be possible.

Relevant items that come to mind right now:

- [x] Clone all existing GitLab repos onto the Artemis server
- [x] Update all Jenkins build plans to replace the Git URLs pointing to GitLab to instead point to Artemis
- [x] Update the Git base URL in the `programming_exercise_details` table in the Artemis database
- [x] User documentation on how to perform the migration

**Comment by krusche** [comment]
The migration from Bitbucket to LocalVC can be found in `chore/bitbucket-localvc-migration-release`. It might be helpful.

**Comment by BaumiCoder** [comment]
Why does the BitBucket to LocalVC Migration uses two extra keys for `@Value`? Both does not seem to be necessary for me:

1. [migration.local-vcs-repo-path](https://github.com/ls1intum/Artemis/blob/7d299a4aae82b1db9f44b1c86965f89c14ad898c/src/main/java/de/tum/in/www1/artemis/config/migration/entries/BitbucketLocalVCMigrationService.java#L22) could be replaced with `artemis.version-control.local-vcs-repo-path`, which already exists at the time of the BitBucket migration (e.g. used [here](https://github.com/ls1intum/Artemis/blob/7d299a4aae82b1db9f44b1c86965f89c14ad898c/src/main/java/de/tum/in/www1/artemis/service/connectors/localvc/LocalVCService.java#L55)).
2. [migration.base-url](https://github.com/ls1intum/Artemis/blob/7d299a4aae82b1db9f44b1c86965f89c14ad898c/src/main/java/de/tum/in/www1/artemis/config/migration/entries/BitbucketLocalVCMigrationService.java#L19) should be always equal to `${server.url}`. Or how can this be different?

@reschandreas can you maybe answer that questions, as the author of the BitBucket to LocalVC migration?

**Comment by reschandreas** [comment]
Hi! I intentionally used different values to ensure that migration requires a deliberate action, preventing it from happening accidentally during updates. This way, the Artemis admin must consciously decide and update their configuration to migrate.

**Comment by b-fein** [comment]
@BaumiCoder I guess with our plan to trigger the migration by a class with a special profile this then serves the same purpose and the different configuration values are not required.

**Comment by BaumiCoder** [comment]
Thanks @reschandreas, with this background information I agree with @b-fein. I moved to the existing values for the migration here (see 55836b787974b38a1b7cc354f96cbf0963bfb91d).

**Comment by BaumiCoder** [comment]
The log message [here](https://github.com/ls1intum/Artemis/blob/7d299a4aae82b1db9f44b1c86965f89c14ad898c/src/main/java/de/tum/in/www1/artemis/config/migration/entries/MigrationEntry20240103_143700.java#L338) claims that the URL will not be changed in the database, because the migration failed. In contrast to this the lines 344 and 345 are also executed in this case, so the URL is saved, isn't? @reschandreas Is that intended or a bug?

**Comment by reschandreas** [comment]
looks like a bug to me. We changed the behaviour of the method several times (we weren't if we should keep the url or not), so this could have slipped through. I'm not aware of any issues during the migration though.

**Comment by BaumiCoder** [comment]
Okay, I fixed that bug (13e0764). However, this bug would have led to an `null` URL in the database (if that is possible). An old URL is still possible if some error blocks the migration of a repository (e.g. the source repository is not available anymore).

**Comment by BaumiCoder** [comment]
Another GitLab specific thing is in the Artemis Database. If tokens are used for the authentication of the users against GitLab, Artemis stores these tokens in the column `vcs_access_token` of `jhi_user`. LocalVC also will have a token authentication (#8664). @SimonEntholzer Will your implementation be able to work with these tokens from GitLab, or should we delete the existing tokens (so that new ones are created if necessary)? I see two differences between the GitLab and the localVC tokens:
1. Prefix: `vcpat-` at localVC / `glpat-` at GitLab
2. Number of the characters after the prefix (digits and letters): actual 40 at localVC / 21 at GitLab (maybe depending on some GitLab configuration)

**Comment by BaumiCoder** [comment]
To make sure that the old tokens do not cause any trouble or became unnecessary data, the migration now removes the token data (da6b3b3).

FYI: @SimonEntholzer

**Comment by BaumiCoder** [comment]
Actual status:

1. There is a migration available with Pull Request #8972 
2. The documentation now contains a [Jenkins-LocalVC section](https://docs.artemis.cit.tum.de/dev/setup/jenkins-localvc.html) and [Jenkins-GitLab section](https://docs.artemis.cit.tum.de/dev/setup/jenkins-gitlab.html) contains a warning that it will get removed.
3. The issue #9318 is about removing the GitLab related parts of Artemis. 

Do we still need this issue here or should we close it?

**Comment by b-fein** [comment]
You are right, I think this can be closed as resolved.

Thanks for the reminder.
